train: /content/drive/MyDrive/myntra-yolov8/data/train
val: /content/drive/MyDrive/myntra-yolov8/data/valid
test: /content/drive/MyDrive/myntra-yolov8/data/test
nc: 3
names: ['accessory', 'jeans', 'top']
