train: /content/drive/MyDrive/yolov8-Vehicle-Detection/data/train
val: /content/drive/MyDrive/yolov8-Vehicle-Detection/data/valid
test: /content/drive/MyDrive/yolov8-Vehicle-Detection/data/test
nc: 9
names: ['car', 'two-wheeler', 'bus', 'tempo', 'truck', 'auto', 'tractor', 'bicycle', 'van']